### ISSUE TITLE
Metadata will not be shown

### ISSUE THREAD

**Issue by gannebamm** [GeoNodeUserGroup-DE/importer-datapackage#5]
### Expected behaviour:
The https://github.com/GeoNodeUserGroup-DE/importer-datapackage/blob/main/importer_datapackage/handlers/datapackage/data/datapackage.json file is used to provide basic metadata for the uploaded tabular data resources. I can edit and see metadata information. This was working and shown in the FOSSGIS 2023 demo:
![grafik](https://github.com/GeoNodeUserGroup-DE/importer-datapackage/assets/6172324/6f69da75-5ae2-4856-9446-cb0a153e3170)

https://av.tib.eu/media/61194 (timestamp 15:51)

### Actual behaviour:
The metadata list is empty, and no attribute information is shown.
![grafik](https://github.com/GeoNodeUserGroup-DE/importer-datapackage/assets/6172324/5f39f0d3-704d-4665-a812-8069eab9843e)

### Setup

GeoNode version: https://github.com/Thuenen-GeoNode-Development/thuenen_atlas/commit/6efe1effeeeab98d5ab8dbc2c02355e5332003fd

used package: https://github.com/GeoNodeUserGroup-DE/importer-datapackage/blob/fae72b44b4de261dd3be287c04ab8bb9508a4a13/importer_datapackage/handlers/datapackage/data/valid_data.zip

**Comment by ridoo** [comment]
Relates to a missing config section in the `localConfig.json`. Just set the `DetailViewer`'s `cfg` section from the `dataset_viewer`. However, this is not related to the actual importer, so I will close it here.

See also: https://github.com/Thuenen-GeoNode-Development/geonode-mapstore-client/pull/36
